[package]
name = "spectrum-cardano-lib"
version = "0.1.0"
edition = "2021"
rust-version = "1.71.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
base16 = "0.2"
cml-chain = { git = "https://github.com/oskin1/cardano-multiplatform-lib.git", branch = "i.oskin/copy-fixed-len-array" }
cml-core = { git = "https://github.com/oskin1/cardano-multiplatform-lib.git", branch = "i.oskin/copy-fixed-len-array" }
cml-crypto = { git = "https://github.com/oskin1/cardano-multiplatform-lib.git", branch = "i.oskin/copy-fixed-len-array" }
serde = { version = "1.0", features = ["derive"] }
hex = "0.4.3"
thiserror = "1.0.47"
derivative = "2.2.0"
lazy_static = "1.4.0"
