[package]
name = "spectrum-cardano-lib"
version = "0.1.0"
edition = "2021"
rust-version = "1.71.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
base16 = "0.2"
cml-chain = { git = "https://github.com/dcSpark/cardano-multiplatform-lib.git", branch = "develop" }
cml-core = { git = "https://github.com/dcSpark/cardano-multiplatform-lib.git", branch = "develop" }
cml-crypto = { git = "https://github.com/dcSpark/cardano-multiplatform-lib.git", branch = "develop" }
cml-multi-era = { git = "https://github.com/dcSpark/cardano-multiplatform-lib.git", branch = "develop" }
serde = { version = "1.0", features = ["derive"] }
hex = "0.4.3"
thiserror = "1.0.47"
derive_more = "0.99.17"
derivative = "2.2.0"
lazy_static = "1.4.0"
linked-hash-map = "0.5.6"
