name: Rust CI for Develop Branch

# Trigger the workflow on push to the develop branch
on:
  push:
    branches:
      - develop

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        override: true

    - name: Cache Cargo registry
      uses: actions/cache@v3
      with:
        path: ~/.cargo/registry
        key: ${{ runner.os }}-cargo-registry-${{ hashFiles('**/Cargo.lock') }}
        restore-keys: |
          ${{ runner.os }}-cargo-registry-

    - name: Cache Cargo build
      uses: actions/cache@v3
      with:
        path: target
        key: ${{ runner.os }}-cargo-build-${{ hashFiles('**/Cargo.lock') }}
        restore-keys: |
          ${{ runner.os }}-cargo-build-

    - name: Build with Cargo
      run: cargo build --package bloom-cardano-agent --bin bloom-cardano-agent
    
    - name: Notify Slack on Success
      if: success()
      env:
        SLACK_WEBHOOK_URL: ${{ https://hooks.slack.com/services/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 }}
        GITHUB_REPOSITORY: ${{ github.repository }}
        GITHUB_WORKFLOW: ${{ github.workflow }}
        GITHUB_RUN_NUMBER: ${{ github.run_number }}
        GITHUB_JOB: ${{ github.job }}
        GITHUB_ACTOR: ${{ github.actor }}
        GITHUB_SHA: ${{ github.sha }}
        GITHUB_REF: ${{ github.ref }}
      run: |
        curl -X POST -H 'Content-type: application/json' --data '{"text":"🎉 Build succeeded for repository: $GITHUB_REPOSITORY, workflow: $GITHUB_WORKFLOW, run: #$GITHUB_RUN_NUMBER. Commit: $GITHUB_SHA by $GITHUB_ACTOR. Check it here: https://github.com/$GITHUB_REPOSITORY/actions/runs/$GITHUB_RUN_NUMBER"}' $SLACK_WEBHOOK_URL

    - name: Notify Slack on Failure
      if: failure()
      env:
        SLACK_WEBHOOK_URL: ${{ https://hooks.slack.com/services/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 }}
        GITHUB_REPOSITORY: ${{ github.repository }}
        GITHUB_WORKFLOW: ${{ github.workflow }}
        GITHUB_RUN_NUMBER: ${{ github.run_number }}
        GITHUB_JOB: ${{ github.job }}
        GITHUB_ACTOR: ${{ github.actor }}
        GITHUB_SHA: ${{ github.sha }}
        GITHUB_REF: ${{ github.ref }}
      run: |
        curl -X POST -H 'Content-type: application/json' --data '{"text":"🚨 Build failed for repository: $GITHUB_REPOSITORY, workflow: $GITHUB_WORKFLOW, run: #$GITHUB_RUN_NUMBER. Commit: $GITHUB_SHA by $GITHUB_ACTOR. Check it here: https://github.com/$GITHUB_REPOSITORY/actions/runs/$GITHUB_RUN_NUMBER"}' $SLACK_WEBHOOK_URL
