name: Rust CI for Develop Branch

# Trigger the workflow on push to the develop branch
on:
  push:
    branches:
      - develop

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        override: true

    - name: Cache Cargo registry
      uses: actions/cache@v3
      with:
        path: ~/.cargo/registry
        key: ${{ runner.os }}-cargo-registry-${{ hashFiles('**/Cargo.lock') }}
        restore-keys: |
          ${{ runner.os }}-cargo-registry-

    - name: Cache Cargo build
      uses: actions/cache@v3
      with:
        path: target
        key: ${{ runner.os }}-cargo-build-${{ hashFiles('**/Cargo.lock') }}
        restore-keys: |
          ${{ runner.os }}-cargo-build-

    - name: Build with Cargo
      run: cargo build --package bloom-cardano-agent --bin bloom-cardano-agent
    
    - name: Run tests
      run: cargo test --package bloom-cardano-agent --bin bloom-cardano-agent
      
    - name: Notify Slack on Success
      if: success()
      run: |
        curl -X POST -H 'Content-type: application/json' --data '{"text":"🎉 Build succeeded!"}' https://hooks.slack.com/services/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

    - name: Notify Slack on Failure
      if: failure()
      run: |
        curl -X POST -H 'Content-type: application/json' --data '{"text":"🚨 Build failed!"}' https://hooks.slack.com/services/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
