name: Notify Slack on Commit

on:
  push:
    branches:
      - develop  # Change this to your desired branch

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Notify Slack on Success
        if: success()
        uses: rtCamp/action-slack-notify@v2.1.1
        with:
          webhook_url: ${{ secrets.SLACK_WEBHOOK }}
          title: 'GitHub Actions - Success 🎉'
          message: |
            *Repository*: <https://github.com/${{ github.repository }}|${{ github.repository }}>
            *Branch*: `${{ github.ref }}`
            *Commit*: <${{ github.event.head_commit.url }}|${{ github.event.head_commit.message }}>
            *Author*: `${{ github.event.head_commit.committer.name }}`
            *Status*: Success
            *Action URL*: <https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}>
          color: good

      - name: Notify Slack on Failure
        if: failure()
        uses: rtCamp/action-slack-notify@v2.1.1
        with:
          webhook_url: ${{ secrets.SLACK_WEBHOOK }}
          title: 'GitHub Actions - Failure ❌'
          message: |
            *Repository*: <https://github.com/${{ github.repository }}|${{ github.repository }}>
            *Branch*: `${{ github.ref }}`
            *Commit*: <${{ github.event.head_commit.url }}|${{ github.event.head_commit.message }}>
            *Author*: `${{ github.event.head_commit.committer.name }}`
            *Status*: Failure
            *Action URL*: <https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}>
          color: danger
  
