name: Test CI for Develop Branch

on:
  push:
    branches:
      - develop

permissions:
  contents: read
  actions: write

jobs:
  slackNotification:
    runs-on: ubuntu-latest

    steps:
      - name: Send notification to Slack
        uses: 8398a7/action-slack@v3
        with:
          status: custom
          fields: workflow, job, commit, author, message, repo, ref
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
          SLACK_COLOR: good
          SLACK_USERNAME: GitHub Actions
          SLACK_TITLE: "New commit on develop branch"
          SLACK_MESSAGE: "A new commit has been pushed to the develop branch. Check it out!"
          SLACK_FOOTER: "Commit Details: ${{ github.sha }} by ${{ github.actor }}"
          SLACK_CHANNEL: "#ci-cd-messages" # replace with your Slack channel name
