name: TEST CI for Develop Branch

on:
  push:
    branches:
      - cicdtest
  
  pull_request:
    branches:
      - cicdtest
    types: [opened, synchronize, closed]    

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        override: true

    - name: Cache Cargo registry
      uses: actions/cache@v3
      with:
        path: ~/.cargo/registry
        key: ${{ runner.os }}-cargo-registry-${{ hashFiles('**/Cargo.lock') }}
        restore-keys: |
          ${{ runner.os }}-cargo-registry-

    - name: Cache Cargo build
      uses: actions/cache@v3
      with:
        path: target
        key: ${{ runner.os }}-cargo-build-${{ hashFiles('**/Cargo.lock') }}
        restore-keys: |
          ${{ runner.os }}-cargo-build-

    - name: Run Cargo fmt
      id: fmt
      run: cargo fmt --all -- --check
      continue-on-error: true

    - name: Notify Slack on fmt result
      if: always()
      uses: slackapi/slack-github-action@v1.22.0
      with:
        payload: |
          {
            "channel": "#your-channel",
            "text": "Cargo fmt result: ${{ job.status }}\nCommit: ${{ github.sha }}\nCommit Message: ${{ github.event.head_commit.message }}\nAuthor: ${{ github.event.head_commit.author.name }}\nBranch: ${{ github.ref }}\nPR: ${{ github.event.pull_request.title }}\nPR URL: ${{ github.event.pull_request.html_url }}",
            "username": "github-actions"
          }
      env:
        SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL2 }}

    - name: Run Cargo Build
      id: build
      run: cargo build --package bloom-cardano-agent --bin bloom-cardano-agent
      continue-on-error: true

    - name: Notify Slack on build result
      if: always()
      uses: slackapi/slack-github-action@v1.22.0
      with:
        payload: |
          {
            "channel": "#your-channel",
            "text": "Cargo build result: ${{ job.status }}\nCommit: ${{ github.sha }}\nCommit Message: ${{ github.event.head_commit.message }}\nAuthor: ${{ github.event.head_commit.author.name }}\nBranch: ${{ github.ref }}\nPR: ${{ github.event.pull_request.title }}\nPR URL: ${{ github.event.pull_request.html_url }}",
            "username": "github-actions"
          }
      env:
        SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL2 }}

    - name: Run tests
      id: test
      run: cargo test --package bloom-cardano-agent --bin bloom-cardano-agent
      continue-on-error: true

    - name: Notify Slack on test result
      if: always()
      uses: slackapi/slack-github-action@v1.22.0
      with:
        payload: |
          {
            "channel": "#your-channel",
            "text": "Cargo test result: ${{ job.status }}\nCommit: ${{ github.sha }}\nCommit Message: ${{ github.event.head_commit.message }}\nAuthor: ${{ github.event.head_commit.author.name }}\nBranch: ${{ github.ref }}\nPR: ${{ github.event.pull_request.title }}\nPR URL: ${{ github.event.pull_request.html_url }}",
            "username": "github-actions"
          }
      env:
        SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL2 }}
