name: TEST CI for Develop Branch

# Trigger the workflow on push to the develop branch
on:
  push:
    branches:
      - cicdtest
  
  pull_request:
    types: [opened, synchronize, closed]    

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        override: true

    - name: Cache Cargo registry
      uses: actions/cache@v3
      with:
        path: ~/.cargo/registry
        key: ${{ runner.os }}-cargo-registry-${{ hashFiles('**/Cargo.lock') }}
        restore-keys: |
          ${{ runner.os }}-cargo-registry-

    - name: Cache Cargo build
      uses: actions/cache@v3
      with:
        path: target
        key: ${{ runner.os }}-cargo-build-${{ hashFiles('**/Cargo.lock') }}
        restore-keys: |
          ${{ runner.os }}-cargo-build-
          
    - name: Run Cargo fmt
      id: fmt
      run: |
        if ! cargo fmt --all -- --check; then
          echo "Cargo fmt failed."
        else
          echo "Cargo fmt succeeded."
        fi
    - name: Run Cargo Build
      id: build
      run: |
        if ! cargo build --package bloom-cardano-agent --bin bloom-cardano-agent; then
          echo "Cargo build failed."
        else
          echo "Cargo build succeeded."
        fi
   
    - name: Run tests
      run: cargo test --package bloom-cardano-agent --bin bloom-cardano-agent
