name: Manual Docker Build and Push

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    
    - name: Add known_hosts
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.KNOWN_HOSTS }}" > ~/.ssh/known_hosts
    
    - name: Deploy to Host
      env:
        SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        HOST: ${{ secrets.HOST4 }}
        SSH_USER: ${{ secrets.SSH_USER }}
      run: |
        echo "${SSH_PRIVATE_KEY}" > private_key
        chmod 600 private_key
        ssh -i private_key ${SSH_USER}@${HOST} << 'EOF'
          touch /root/TEST/test.txt
        EOF
      shell: bash
